# Project information
site_name: 'IoTaaP Console API'
site_description: 'IoTaaP API Docs'
repo_url: 'https://github.com/iotaap/docs-rest'
nav:
  - Home: index.md
  - Authentication: authentication.md
  - User: user.md
  - Settings: settings.md
  - Devices: devices.md
  - Groups: groups.md
  - Device OTA: deviceOta.md
  - Group OTA: groupOta.md
  - MQTT: mqtt.md
  - MQTT REST Bridge: mqttRest.md
  - Billing: billing.md
        
# Copyright
copyright: 'Copyright IoTaaP'

theme: 
    name: material
    palette:
        primary: 'light-blue'
        accent: 'deep-purple'
#    font:
#        text: 'Ubuntu'
#        code: 'Ubuntu Mono'
    logo: 'images/logo.png'
    favicon: 'images/favicon.png'
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  social:
    - type: 'github'
      link: 'https://github.com/iotaap'
    - type: 'twitter'
      link: 'https://twitter.com/iotaap'
    - type: 'facebook'
      link: 'https://www.facebook.com/iotaap'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCC9hU3ndh6bh-LbW3YjI98g'