# Project information
site_name: 'IoTaaP Console API'
site_description: 'IoTaaP API Docs'
repo_url: 'https://github.com/iotaap/docs-rest'
nav:
  - Home: index.md
  - Authentication: authentication.md
  - User: user.md
  - Settings: settings.md
  - Devices: devices.md
  - Groups: groups.md
  - Device OTA: deviceOta.md
  - Group OTA: groupOta.md
  - MQTT: mqtt.md
  - MQTT REST Bridge: mqttRest.md
  - Billing: billing.md
        
copyright: 'Copyright &copy; IoTaaP'

theme: 
    name: material
    palette:
        primary: 'light-blue'
        accent: 'deep-purple'
    logo: 'images/logo.png'
    favicon: 'images/favicon.png'

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/iotaap
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/iotaap
      name: Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/iotaap
      name: Facebook
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCC9hU3ndh6bh-LbW3YjI98g
      name: YouTube